### ISSUE TITLE
flash-shelly.py error

### ISSUE THREAD

**Issue by Snekatis** [mongoose-os-apps/shelly-homekit#1549]
Environment:
	•	OS: macOS
	•	Python Version: 3.13.0
	•	flash-shelly Version: 3.0.0
Error: 
flash-shelly version: 3.0.0
Try to update your script, maybe the bug is already fixed!
Traceback (most recent call last):
  File "/Users/ondrej.stepanek/Downloads/shelly-homekit-master/tools/flash-shelly.py", line 1200, in run_app
    self.device_scan()
    ~~~~~~~~~~~~~~~~^^
  File "/Users/ondrej.stepanek/Downloads/shelly-homekit-master/tools/flash-shelly.py", line 1703, in device_scan
    self.probe_device(device)
    ~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/ondrej.stepanek/Downloads/shelly-homekit-master/tools/flash-shelly.py", line 1646, in probe_device
    self.parse_info(device, hk_flash_fw_version)  # main convert run, or update stock to the latest firmware if an update or color mode is required.
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ondrej.stepanek/Downloads/shelly-homekit-master/tools/flash-shelly.py", line 1404, in parse_info
    download_url_request = requests.head(download_url)
  File "/opt/homebrew/lib/python3.13/site-packages/requests/api.py", line 100, in head
    return request("head", url, **kwargs)
  File "/opt/homebrew/lib/python3.13/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.13/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/opt/homebrew/lib/python3.13/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
    ~~~~~~~~~^
        method=request.method.upper(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
        hooks=merge_hooks(request.hooks, self.hooks),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/homebrew/lib/python3.13/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.13/site-packages/requests/models.py", line 438, in prepare_url
    raise MissingSchema(
    ...<2 lines>...
    )
requests.exceptions.MissingSchema: Invalid URL 'invalid': No scheme supplied. Perhaps you meant https://invalid?

**Comment by markirb** [comment]
it is not a failure in the script but the url which I deliberately set to something without uri. I added an URI now, should not happen anymore
