### ISSUE TITLE
flash_shelly.py error

### ISSUE THREAD

**Issue by geoigeek** [mongoose-os-apps/shelly-homekit#285]
Hello,

i want to use the Flash Script for the first time on my MBP 11.0.1

But i get the following Error. What does it mean?

```
./flash_shelly.py -la
Scanning for Shelly devices...

Traceback (most recent call last):
  File "/Users/alex/Downloads/shelly-homekit-master/tools/./flash_shelly.py", line 539, in <module>
    device_scan(args.hosts, action, args.do_all, args.dry_run, args.silent_run, args.mode, args.exclude, args.version, args.variant, stock_release_info, homekit_release_info)
  File "/Users/alex/Downloads/shelly-homekit-master/tools/./flash_shelly.py", line 469, in device_scan
    parse_info(device, action, dry_run, silent_run, mode, exclude, version, variant, stock_release_info, homekit_release_info)
  File "/Users/alex/Downloads/shelly-homekit-master/tools/./flash_shelly.py", line 312, in parse_info
    stock_model = device_info['stock_model']
KeyError: 'stock_model'
```
Thx

**Comment by andyblac** [comment]
please rerun with `./flash_shelly.py -la -v=1` and post results, thx

**Comment by geoigeek** [comment]
here are the results

```
./flash_shelly.py -la -v=1
app
OS: Darwin
action: list
mode: homekit
do_all: True
dry_run: False
silent_run: False
mode: homekit
version: False
exclude: None
variant: False
verbose: 1
hosts: []

stock_release_info:{'isok': True, 'data': {'SHPLG-1': {'url': 'http://api.shelly.cloud/firmware/SHPLG-1.zip', 'version': '20200827-065544/v1.8.3@4a8bc427'}, 'SHPLG-S': {'url': 'http://api.shelly.cloud/firmware/SHPLG-S.zip', 'version': '20200827-070306/v1.8.3@4a8bc427'}, 'SHPLG-U1': {'url': 'http://api.shelly.cloud/firmware/SHPLG-U1.zip', 'version': '20200827-070340/v1.8.3@4a8bc427'}, 'SHPLG2-1': {'url': 'http://api.shelly.cloud/firmware/SHPLG2-1.zip', 'version': '20200827-070415/v1.8.3@4a8bc427'}, 'SHSW-1': {'url': 'http://api.shelly.cloud/firmware/SHSW-1.zip', 'version': '20200827-065344/v1.8.3@4a8bc427'}, 'SHSW-21': {'url': 'http://api.shelly.cloud/firmware/SHSW-21.zip', 'version': '20200827-065420/v1.8.3@4a8bc427'}, 'SHSW-25': {'url': 'http://api.shelly.cloud/firmware/SHSW-25.zip', 'version': '20200827-065456/v1.8.3@4a8bc427'}, 'SHSW-PM': {'url': 'http://api.shelly.cloud/firmware/SHSW-PM.zip', 'version': '20200827-070450/v1.8.3@4a8bc427'}, 'SHAIR-1': {'url': 'http://api.shelly.cloud/firmware/SHAIR-1.zip', 'version': '20200812-092044/v1.8.0@8acf41b0'}, 'SHSW-44': {'url': 'http://api.shelly.cloud/firmware/SHSW-44.zip', 'version': '20201019-110845/v1.6.6_4Pro@bad181e4'}, 'SHUNI-1': {'url': 'http://api.shelly.cloud/firmware/SHUNI-1.zip', 'version': '20200826-111450/1206-production-ShellyUNI@a80ee1fc+'}, 'SHEM': {'url': 'http://api.shelly.cloud/firmware/SHEM.zip', 'version': '20200813-140346/v1.8.1@1b2a49be'}, 'SHEM-3': {'url': 'http://api.shelly.cloud/firmware/SHEM-3.zip', 'version': '20200813-140420/v1.8.1@1b2a49be'}, 'SHSEN-1': {'url': 'http://api.shelly.cloud/firmware/SHSEN-1_build.zip', 'version': '20200717-112934/v1.7.7@a02db0b8'}, 'SHGS-1': {'url': 'http://api.shelly.cloud/firmware/SHGS-1.zip', 'version': '20200812-092502/v1.8.0@8acf41b0'}, 'SHSM-01': {'url': 'http://api.shelly.cloud/firmware/SHSM-01.zip', 'version': '20200812-091144/v1.8.0@8acf41b0'}, 'SHHT-1': {'url': 'http://api.shelly.cloud/firmware/SHHT-1.zip', 'version': '20200812-091311/v1.8.0@8acf41b0'}, 'SHWT-1': {'url': 'http://api.shelly.cloud/firmware/SHWT-1.zip', 'version': '20200812-091355/v1.8.0@8acf41b0'}, 'SHDW-1': {'url': 'http://api.shelly.cloud/firmware/SHDW-1.zip', 'version': '20200818-120325/v1.8.2@36539b0b', 'beta_url': 'http://api.shelly.cloud/firmware/rc/SHDW-1.zip', 'beta_ver': '20200814-174756/v1.8.2-rc1@59a25feb'}, 'SHDW-2': {'url': 'http://api.shelly.cloud/firmware/SHDW-2.zip', 'version': '20200818-120407/v1.8.2@36539b0b', 'beta_url': 'http://api.shelly.cloud/firmware/rc/SHDW-2.zip', 'beta_ver': '20200814-174839/v1.8.2-rc1@59a25feb'}, 'SHSPOT-1': {'url': 'http://api.shelly.cloud/firmware/SHSPOT-1.zip', 'version': '20200812-090754/v1.8.0@8acf41b0'}, 'SHCL-255': {'url': 'http://api.shelly.cloud/firmware/compatibility/SHCL-255/0.2.0-73a40eef.zip', 'version': '20180116-161402/v0.2.0@73a40eef'}, 'SHBLB-1': {'url': 'http://api.shelly.cloud/firmware/SHBLB-1.zip', 'version': '20200812-090503/v1.8.0@8acf41b0'}, 'SHCB-1': {'url': 'http://api.shelly.cloud/firmware/SHCB-1.zip', 'version': '20200812-090429/v1.8.0@8acf41b0'}, 'SHRGBW2': {'url': 'http://api.shelly.cloud/firmware/SHRGBW2.zip', 'version': '20200827-070122/v1.8.3@4a8bc427'}, 'SHRGBWW-01': {'url': 'http://api.shelly.cloud/firmware/SHRGBWW-01.zip', 'version': '20200827-065125/v1.8.3@4a8bc427'}, 'SH2LED-1': {'url': 'http://api.shelly.cloud/firmware/SH2LED-1.zip', 'version': '20200812-090719/v1.8.0@8acf41b0'}, 'SHDM-1': {'url': 'http://api.shelly.cloud/firmware/SHDM-1.zip', 'version': '20201007-085347/v1.8.5@5fbcbaa3'}, 'SHDM-2': {'url': 'http://api.shelly.cloud/firmware/SHDM-2.zip', 'version': '20201007-085431/v1.8.5@5fbcbaa3'}, 'SHDIMW-1': {'url': 'http://api.shelly.cloud/firmware/SHDIMW-1.zip', 'version': '20200812-092244/v1.8.0@8acf41b0'}, 'SHVIN-1': {'url': 'http://api.shelly.cloud/firmware/SHVIN-1.zip', 'version': '20200827-065016/v1.8.3@4a8bc427'}, 'SHBDUO-1': {'url': 'http://api.shelly.cloud/firmware/SHBDUO-1.zip', 'version': '20200827-065050/v1.8.3@4a8bc427'}, 'SHBTN-1': {'url': 'http://api.shelly.cloud/firmware/SHBTN-1.zip', 'version': '20200827-070047/v1.8.3@4a8bc427'}, 'SHIX3-1': {'url': 'http://api.shelly.cloud/firmware/SHIX3-1.zip', 'version': '20200827-070910/v1.8.3@4a8bc427'}}}

homekit_release_info:[['X^2.5.0-.*', {'version': '2.5.0-beta2', 'rel_notes': 'https://github.com/mongoose-os-apps/shelly-homekit/issues/254#issuecomment-723514784', 'rel_notesX': '', 'urls': {'Shelly1': 'https://rojer.me/files/shelly/2.5.0-beta2/shelly-homekit-Shelly1.zip', 'Shelly1PM': 'https://rojer.me/files/shelly/2.5.0-beta2/shelly-homekit-Shelly1PM.zip', 'Shelly2': 'https://rojer.me/files/shelly/2.5.0-beta2/shelly-homekit-Shelly2.zip', 'Shelly25': 'https://rojer.me/files/shelly/2.5.0-beta2/shelly-homekit-Shelly25.zip', 'ShellyI3': 'https://rojer.me/files/shelly/2.5.0-beta2/shelly-homekit-ShellyI3.zip', 'ShellyPlug': 'https://rojer.me/files/shelly/2.5.0-beta2/shelly-homekit-ShellyPlug.zip', 'ShellyPlugS': 'https://rojer.me/files/shelly/2.5.0-beta2/shelly-homekit-ShellyPlugS.zip'}}], ['.*', {'version': '2.5.0', 'rel_notes': 'https://github.com/mongoose-os-apps/shelly-homekit/releases/tag/2.5.0', 'urls': {'Shelly1': 'https://rojer.me/files/shelly/2.5.0/shelly-homekit-Shelly1.zip', 'Shelly1PM': 'https://rojer.me/files/shelly/2.5.0/shelly-homekit-Shelly1PM.zip', 'Shelly2': 'https://rojer.me/files/shelly/2.5.0/shelly-homekit-Shelly2.zip', 'Shelly25': 'https://rojer.me/files/shelly/2.5.0/shelly-homekit-Shelly25.zip', 'ShellyI3': 'https://rojer.me/files/shelly/2.5.0/shelly-homekit-ShellyI3.zip', 'Shelly-i3': 'https://rojer.me/files/shelly/2.5.0/shelly-homekit-ShellyI3.zip', 'ShellyPlug': 'https://rojer.me/files/shelly/2.5.0/shelly-homekit-ShellyPlug.zip', 'ShellyPlugS': 'https://rojer.me/files/shelly/2.5.0/shelly-homekit-ShellyPlugS.zip'}}]]

device_scan
devices: []
action: list
do_all: True
dry_run: False
silent_run: False
mode: homekit
exclude: None
version: False
variant: False
Scanning for Shelly devices...

Valid Hostname: shellyswitch25-112C8F True
Info: {'type': 'SHSW-25', 'mac': 'C82B96112C8F', 'auth': False, 'fw': '20200812-091015/v1.8.0@8acf41b0', 'num_outputs': 2, 'num_meters': 2, 'num_rollers': 1, 'host': 'shellyswitch25-112C8F.local', 'device_id': 'shellyswitch25-112C8F', 'model': 'Shelly25', 'stock_model': 'SHSW-25', 'version': '1.8.0', 'fw_type': 'stock', 'fw_type_str': 'Official'}
Valid Hostname: HP Officejet Pro X476dw MFP False
Valid Hostname: shelly1-A4CF12F45BF2 True
Info: {'id': 'shelly1-A4CF12F45BF2', 'app': 'switch1', 'host': 'shelly1-A4CF12F45BF2.local', 'version': '2.0.12', 'fw_build': '20200805-094422/2.0.12-gee52eca-master', 'uptime': 53971, 'sw1': {'id': 0, 'name': 'Shelly SW-VG6', 'type': 0, 'in_mode': 1, 'initial': 3, 'state': False, 'auto_off': False, 'auto_off_delay': 0.0}, 'wifi_en': True, 'wifi_ssid': 'wifissid', 'wifi_pass': 'xxxwifisecretxxx', 'hap_provisioned': True, 'hap_paired': True, 'hap_ip_conns_pending': 0, 'hap_ip_conns_active': 8, 'hap_ip_conns_max': 9, 'device_id': 'shelly1-A4CF12F45BF2', 'model': 'Shelly1', 'fw_type': 'homekit', 'fw_type_str': 'HomeKit'}
Valid Hostname: shellyswitch25-F3452C True
Info: {'type': 'SHSW-25', 'mac': '98F4ABF3452C', 'auth': False, 'fw': '20200812-091015/v1.8.0@8acf41b0', 'num_outputs': 2, 'num_meters': 2, 'num_rollers': 1, 'host': 'shellyswitch25-F3452C.local', 'device_id': 'shellyswitch25-F3452C', 'model': 'Shelly25', 'stock_model': 'SHSW-25', 'version': '1.8.0', 'fw_type': 'stock', 'fw_type_str': 'Official'}
Valid Hostname: shelly1-A4CF12F41418 True
Info: {'device_id': 'shelly1-F41418', 'name': 'shelly1-A4CF12F41418', 'app': 'switch1', 'model': 'Shelly1', 'stock_model': 'SHSW-1', 'host': 'shelly1-A4CF12F41418.local', 'version': '2.5.0', 'fw_build': '20201109-203842/2.5.0-g42dbdba-master', 'uptime': 53974, 'wifi_en': True, 'wifi_ssid': 'wifissid', 'wifi_pass': '***', 'wifi_rssi': -85, 'wifi_ip': '192.168.248.182', 'hap_cn': 3, 'hap_running': True, 'hap_paired': True, 'hap_ip_conns_pending': 0, 'hap_ip_conns_active': 8, 'hap_ip_conns_max': 9, 'sys_mode': 0, 'rsh_avail': False, 'gdo_avail': True, 'debug_en': False, 'components': [{'id': 1, 'type': 0, 'name': 'Shelly SW-VG4', 'svc_type': 0, 'in_mode': 1, 'initial': 3, 'state': True, 'auto_off': False, 'auto_off_delay': 0.0}], 'fw_type': 'homekit', 'fw_type_str': 'HomeKit'}
Valid Hostname: shelly1-B97B21 True
Info: {'device_id': 'shelly1-B97B21', 'name': 'shelly1-B97B21', 'app': 'switch1', 'model': 'Shelly1', 'stock_model': 'SHSW-1', 'host': 'shelly1-B97B21.local', 'version': '2.5.0', 'fw_build': '20201109-203842/2.5.0-g42dbdba-master', 'uptime': 55232, 'wifi_en': True, 'wifi_ssid': 'wifissid', 'wifi_pass': '***', 'wifi_rssi': -82, 'wifi_ip': '192.168.248.199', 'hap_cn': 5, 'hap_running': True, 'hap_paired': True, 'hap_ip_conns_pending': 0, 'hap_ip_conns_active': 8, 'hap_ip_conns_max': 9, 'sys_mode': 0, 'rsh_avail': False, 'gdo_avail': True, 'debug_en': False, 'components': [{'id': 1, 'type': 0, 'name': 'Shelly SW-VG2', 'svc_type': 1, 'in_mode': 1, 'initial': 3, 'state': False, 'auto_off': False, 'auto_off_delay': 0.0}], 'fw_type': 'homekit', 'fw_type_str': 'HomeKit'}
Valid Hostname: shelly1-A4CF12F40A25 True
Info: {'id': 'shelly1-A4CF12F40A25', 'app': 'switch1', 'host': 'shelly1-A4CF12F40A25.local', 'version': '2.0.12', 'fw_build': '20200805-094422/2.0.12-gee52eca-master', 'uptime': 547041, 'sw1': {'id': 0, 'name': 'Shelly SW-VG8', 'type': 1, 'in_mode': 1, 'initial': 3, 'state': False, 'auto_off': False, 'auto_off_delay': 0.0}, 'wifi_en': True, 'wifi_ssid': 'wifissid', 'wifi_pass': 'xxxwifisecretxxx', 'hap_provisioned': True, 'hap_paired': True, 'hap_ip_conns_pending': 0, 'hap_ip_conns_active': 8, 'hap_ip_conns_max': 9, 'device_id': 'shelly1-A4CF12F40A25', 'model': 'Shelly1', 'fw_type': 'homekit', 'fw_type_str': 'HomeKit'}
Valid Hostname: Brother QL-710W False
Valid Hostname: shelly1-A4CF12F40A27 True
Info: {'id': 'shelly1-A4CF12F40A27', 'app': 'switch1', 'host': 'shelly1-A4CF12F40A27.local', 'version': '2.0.12', 'fw_build': '20200805-094422/2.0.12-gee52eca-master', 'uptime': 122374, 'sw1': {'id': 0, 'name': 'Shelly SW-VG7', 'type': 1, 'in_mode': 1, 'initial': 3, 'state': False, 'auto_off': False, 'auto_off_delay': 0.0}, 'wifi_en': True, 'wifi_ssid': 'wifissid', 'wifi_pass': 'xxxwifisecretxxx', 'hap_provisioned': True, 'hap_paired': True, 'hap_ip_conns_pending': 0, 'hap_ip_conns_active': 8, 'hap_ip_conns_max': 9, 'device_id': 'shelly1-A4CF12F40A27', 'model': 'Shelly1', 'fw_type': 'homekit', 'fw_type_str': 'HomeKit'}
Valid Hostname: shellyswitch25-110822 True
Info: {'type': 'SHSW-25', 'mac': 'C82B96110822', 'auth': False, 'fw': '20200812-091015/v1.8.0@8acf41b0', 'num_outputs': 2, 'num_meters': 2, 'num_rollers': 1, 'host': 'shellyswitch25-110822.local', 'device_id': 'shellyswitch25-110822', 'model': 'Shelly25', 'stock_model': 'SHSW-25', 'version': '1.8.0', 'fw_type': 'stock', 'fw_type_str': 'Official'}
Valid Hostname: shellydimmer-D18319 True
Info: {'type': 'SHDM-1', 'mac': '98F4ABD18319', 'auth': False, 'fw': '20200812-092126/v1.8.0@8acf41b0', 'num_outputs': 1, 'num_meters': 1, 'host': 'shellydimmer-D18319.local', 'device_id': 'shellydimmer-D18319', 'model': 'ShellyDimmer1', 'stock_model': 'SHDM-1', 'version': '1.8.0', 'fw_type': 'stock', 'fw_type_str': 'Official'}
device_test: [{'id': 'shelly1-A4CF12F40A25', 'app': 'switch1', 'host': 'shelly1-A4CF12F40A25.local', 'version': '2.0.12', 'fw_build': '20200805-094422/2.0.12-gee52eca-master', 'uptime': 547041, 'sw1': {'id': 0, 'name': 'Shelly SW-VG8', 'type': 1, 'in_mode': 1, 'initial': 3, 'state': False, 'auto_off': False, 'auto_off_delay': 0.0}, 'wifi_en': True, 'wifi_ssid': 'wifissid', 'wifi_pass': 'xxxwifisecretxxx', 'hap_provisioned': True, 'hap_paired': True, 'hap_ip_conns_pending': 0, 'hap_ip_conns_active': 8, 'hap_ip_conns_max': 9, 'device_id': 'shelly1-A4CF12F40A25', 'model': 'Shelly1', 'fw_type': 'homekit', 'fw_type_str': 'HomeKit'}, {'id': 'shelly1-A4CF12F40A27', 'app': 'switch1', 'host': 'shelly1-A4CF12F40A27.local', 'version': '2.0.12', 'fw_build': '20200805-094422/2.0.12-gee52eca-master', 'uptime': 122374, 'sw1': {'id': 0, 'name': 'Shelly SW-VG7', 'type': 1, 'in_mode': 1, 'initial': 3, 'state': False, 'auto_off': False, 'auto_off_delay': 0.0}, 'wifi_en': True, 'wifi_ssid': 'wifissid', 'wifi_pass': 'xxxwifisecretxxx', 'hap_provisioned': True, 'hap_paired': True, 'hap_ip_conns_pending': 0, 'hap_ip_conns_active': 8, 'hap_ip_conns_max': 9, 'device_id': 'shelly1-A4CF12F40A27', 'model': 'Shelly1', 'fw_type': 'homekit', 'fw_type_str': 'HomeKit'}, {'device_id': 'shelly1-F41418', 'name': 'shelly1-A4CF12F41418', 'app': 'switch1', 'model': 'Shelly1', 'stock_model': 'SHSW-1', 'host': 'shelly1-A4CF12F41418.local', 'version': '2.5.0', 'fw_build': '20201109-203842/2.5.0-g42dbdba-master', 'uptime': 53974, 'wifi_en': True, 'wifi_ssid': 'wifissid', 'wifi_pass': '***', 'wifi_rssi': -85, 'wifi_ip': '192.168.248.182', 'hap_cn': 3, 'hap_running': True, 'hap_paired': True, 'hap_ip_conns_pending': 0, 'hap_ip_conns_active': 8, 'hap_ip_conns_max': 9, 'sys_mode': 0, 'rsh_avail': False, 'gdo_avail': True, 'debug_en': False, 'components': [{'id': 1, 'type': 0, 'name': 'Shelly SW-VG4', 'svc_type': 0, 'in_mode': 1, 'initial': 3, 'state': True, 'auto_off': False, 'auto_off_delay': 0.0}], 'fw_type': 'homekit', 'fw_type_str': 'HomeKit'}, {'id': 'shelly1-A4CF12F45BF2', 'app': 'switch1', 'host': 'shelly1-A4CF12F45BF2.local', 'version': '2.0.12', 'fw_build': '20200805-094422/2.0.12-gee52eca-master', 'uptime': 53971, 'sw1': {'id': 0, 'name': 'Shelly SW-VG6', 'type': 0, 'in_mode': 1, 'initial': 3, 'state': False, 'auto_off': False, 'auto_off_delay': 0.0}, 'wifi_en': True, 'wifi_ssid': 'wifissid', 'wifi_pass': 'xxxwifisecretxxx', 'hap_provisioned': True, 'hap_paired': True, 'hap_ip_conns_pending': 0, 'hap_ip_conns_active': 8, 'hap_ip_conns_max': 9, 'device_id': 'shelly1-A4CF12F45BF2', 'model': 'Shelly1', 'fw_type': 'homekit', 'fw_type_str': 'HomeKit'}, {'device_id': 'shelly1-B97B21', 'name': 'shelly1-B97B21', 'app': 'switch1', 'model': 'Shelly1', 'stock_model': 'SHSW-1', 'host': 'shelly1-B97B21.local', 'version': '2.5.0', 'fw_build': '20201109-203842/2.5.0-g42dbdba-master', 'uptime': 55232, 'wifi_en': True, 'wifi_ssid': 'wifissid', 'wifi_pass': '***', 'wifi_rssi': -82, 'wifi_ip': '192.168.248.199', 'hap_cn': 5, 'hap_running': True, 'hap_paired': True, 'hap_ip_conns_pending': 0, 'hap_ip_conns_active': 8, 'hap_ip_conns_max': 9, 'sys_mode': 0, 'rsh_avail': False, 'gdo_avail': True, 'debug_en': False, 'components': [{'id': 1, 'type': 0, 'name': 'Shelly SW-VG2', 'svc_type': 1, 'in_mode': 1, 'initial': 3, 'state': False, 'auto_off': False, 'auto_off_delay': 0.0}], 'fw_type': 'homekit', 'fw_type_str': 'HomeKit'}, {'type': 'SHDM-1', 'mac': '98F4ABD18319', 'auth': False, 'fw': '20200812-092126/v1.8.0@8acf41b0', 'num_outputs': 1, 'num_meters': 1, 'host': 'shellydimmer-D18319.local', 'device_id': 'shellydimmer-D18319', 'model': 'ShellyDimmer1', 'stock_model': 'SHDM-1', 'version': '1.8.0', 'fw_type': 'stock', 'fw_type_str': 'Official'}, {'type': 'SHSW-25', 'mac': 'C82B96110822', 'auth': False, 'fw': '20200812-091015/v1.8.0@8acf41b0', 'num_outputs': 2, 'num_meters': 2, 'num_rollers': 1, 'host': 'shellyswitch25-110822.local', 'device_id': 'shellyswitch25-110822', 'model': 'Shelly25', 'stock_model': 'SHSW-25', 'version': '1.8.0', 'fw_type': 'stock', 'fw_type_str': 'Official'}, {'type': 'SHSW-25', 'mac': 'C82B96112C8F', 'auth': False, 'fw': '20200812-091015/v1.8.0@8acf41b0', 'num_outputs': 2, 'num_meters': 2, 'num_rollers': 1, 'host': 'shellyswitch25-112C8F.local', 'device_id': 'shellyswitch25-112C8F', 'model': 'Shelly25', 'stock_model': 'SHSW-25', 'version': '1.8.0', 'fw_type': 'stock', 'fw_type_str': 'Official'}, {'type': 'SHSW-25', 'mac': '98F4ABF3452C', 'auth': False, 'fw': '20200812-091015/v1.8.0@8acf41b0', 'num_outputs': 2, 'num_meters': 2, 'num_rollers': 1, 'host': 'shellyswitch25-F3452C.local', 'device_id': 'shellyswitch25-F3452C', 'model': 'Shelly25', 'stock_model': 'SHSW-25', 'version': '1.8.0', 'fw_type': 'stock', 'fw_type_str': 'Official'}]

parse_info
device_info: {'id': 'shelly1-A4CF12F40A25', 'app': 'switch1', 'host': 'shelly1-A4CF12F40A25.local', 'version': '2.0.12', 'fw_build': '20200805-094422/2.0.12-gee52eca-master', 'uptime': 547041, 'sw1': {'id': 0, 'name': 'Shelly SW-VG8', 'type': 1, 'in_mode': 1, 'initial': 3, 'state': False, 'auto_off': False, 'auto_off_delay': 0.0}, 'wifi_en': True, 'wifi_ssid': 'wifissid', 'wifi_pass': 'xxxwifisecretxxx', 'hap_provisioned': True, 'hap_paired': True, 'hap_ip_conns_pending': 0, 'hap_ip_conns_active': 8, 'hap_ip_conns_max': 9, 'device_id': 'shelly1-A4CF12F40A25', 'model': 'Shelly1', 'fw_type': 'homekit', 'fw_type_str': 'HomeKit'}
Traceback (most recent call last):
  File "/Users/alex/Downloads/shelly-homekit-master/tools/./flash_shelly.py", line 539, in <module>
    device_scan(args.hosts, action, args.do_all, args.dry_run, args.silent_run, args.mode, args.exclude, args.version, args.variant, stock_release_info, homekit_release_info)
  File "/Users/alex/Downloads/shelly-homekit-master/tools/./flash_shelly.py", line 469, in device_scan
    parse_info(device, action, dry_run, silent_run, mode, exclude, version, variant, stock_release_info, homekit_release_info)
  File "/Users/alex/Downloads/shelly-homekit-master/tools/./flash_shelly.py", line 312, in parse_info
    stock_model = device_info['stock_model']
KeyError: 'stock_model'
```

**Comment by andyblac** [comment]
ok, your on a fairly old version (2.0.12) this version did not include the required infomation for the script, please update via the webUI, then the script should work. i'll add in a version check to stop crash thanks.
