### ISSUE TITLE
parse_version fails with 20210318-141759/v1.10.0-geba262d

### ISSUE THREAD

**Issue by juanfal** [mongoose-os-apps/shelly-homekit#588]
It does a strict regexp analysis that doesn't match 20210318-141759/v1.10.0-geba262d…

    Traceback (most recent call last):
      File "flash-shelly.py", line 1244, in <module>
        main.device_scan()
      File "flash-shelly.py", line 1086, in device_scan
        self.probe_device(device)
      File "flash-shelly.py", line 1000, in probe_device
        if (deviceinfo.fw_version == '0.0.0' or self.is_newer(deviceinfo.flash_fw_version, deviceinfo.fw_version)):
      File "flash-shelly.py", line 606, in is_newer
        vi1 = self.parse_version(v1)
      File "flash-shelly.py", line 597, in parse_version
        major = int(v.group('major'))
    AttributeError: 'NoneType' object has no attribute 'group'

**Comment by andyblac** [comment]
this should be fixed in 2.6.2 version in git.
